// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Super.Models;

#nullable disable

namespace Super.Migrations
{
    [DbContext(typeof(QlbhContext))]
    partial class QlbhContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Super.Models.Balance", b =>
                {
                    b.Property<string>("Url")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Details")
                        .HasColumnType("ntext");

                   

                    b.Property<string>("Km")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KM");

                    b.HasKey("Url");

                    

                    b.ToTable("Balance");
                });

            modelBuilder.Entity("Super.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<int>("MaHang")
                        .HasColumnType("int");

                    b.Property<string>("DonGiaBan")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("SoLuongMua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("ThanhTien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("MaHd", "MaHang");

                    b.HasIndex("MaHang");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("Super.Models.Hang", b =>
                {
                    b.Property<int>("MaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHang"));

                    b.Property<string>("DonGiaHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Filter")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComputedColumnSql("LOWER([MaKhoa] + [TenKhoa] + [SDT])");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanHieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("ntext");

                    b.Property<string>("Src")
                        .HasColumnType("ntext");

                    b.Property<string>("TenHang")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("TonKho")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHang");

                    b.HasIndex("MaNhanHieu");

                    b.HasIndex("Url");

                    b.ToTable("Hang");
                });

            modelBuilder.Entity("Super.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHd"));

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<DateTime?>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaHd");

                    b.HasIndex("MaKh");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("Super.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaKh");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("Super.Models.NhaCungCap", b =>
                {
                    b.Property<string>("MaCungCap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNhaCungCap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCungCap");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("Super.Models.NhanHieu", b =>
                {
                    b.Property<string>("MaNhanHieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaCungCap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNhanHieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNhanHieu");

                    b.HasIndex("MaCungCap");

                    b.ToTable("NhanHieu");
                });

            modelBuilder.Entity("Super.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.HasKey("UserId");

                    b.HasIndex("MaKh");

                    b.ToTable("Users");
                });

       

            modelBuilder.Entity("Super.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("Super.Models.Hang", "MaHangNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHang")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietHoaDon_Hang");

                    b.HasOne("Super.Models.HoaDon", "MaHdNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietHoaDon_HoaDon");

                    b.Navigation("MaHangNavigation");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("Super.Models.Hang", b =>
                {
                    b.HasOne("Super.Models.NhanHieu", "MaNhanHieuNavigation")
                        .WithMany("Hangs")
                        .HasForeignKey("MaNhanHieu")
                        .HasConstraintName("FK_Hang_NhanHieu");

                    b.HasOne("Super.Models.Balance", "UrlNavigation")
                        .WithMany("Hangs")
                        .HasForeignKey("Url")
                        .HasConstraintName("FK_Hang_Balance");

                    b.Navigation("MaNhanHieuNavigation");

                    b.Navigation("UrlNavigation");
                });

            modelBuilder.Entity("Super.Models.HoaDon", b =>
                {
                    b.HasOne("Super.Models.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_HoaDon_KhachHang");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("Super.Models.NhanHieu", b =>
                {
                    b.HasOne("Super.Models.NhaCungCap", "MaCungCapNavigation")
                        .WithMany("NhanHieus")
                        .HasForeignKey("MaCungCap")
                        .HasConstraintName("FK_NhanHieu_NhaCungCap");

                    b.Navigation("MaCungCapNavigation");
                });

            modelBuilder.Entity("Super.Models.User", b =>
                {
                    b.HasOne("Super.Models.KhachHang", "MaKhNavigation")
                        .WithMany("Users")
                        .HasForeignKey("MaKh");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("Super.Models.Balance", b =>
                {
                    b.Navigation("Hangs");
                });

            modelBuilder.Entity("Super.Models.Hang", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("KMDB");
                });

            modelBuilder.Entity("Super.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("Super.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Super.Models.NhaCungCap", b =>
                {
                    b.Navigation("NhanHieus");
                });

            modelBuilder.Entity("Super.Models.NhanHieu", b =>
                {
                    b.Navigation("Hangs");
                });
#pragma warning restore 612, 618
        }
    }
}
